version: '3.4'

include:
  - docker-compose.db.yml

services:
  fumble.discount.grpc:
    image: ${DOCKER_REGISTRY-}fumblediscountgrpc
    build:
      context: .
      dockerfile: Fumble.Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DISCOUNT_DB_CONNECTION_STRING=mongodb://root:root12345@fumble.discount.database/
      - DISCOUNT_DB_NAME=fumble_discount_db
      - DISCOUNT_DB_COUPONS_COLLECTION=coupons
      
    ports:
      - "8050:8080"